AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100
  IgnoredPatterns: ['\A\s*#']

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Rails:
  Enabled: true
